#!/usr/bin/env bash
# gen-maintenance-inventory.sh — maintenance envanterini URETIR (elle yazilmaz)
#
# SADECE chef.sh'ten cagrilir — bagimsiz calistirilmaz. Garage IP'si argumanla
# gelir (chef bilir: mevcut CT'den pct config ya da fresh secim); .env'de IP
# state'i tutulmaz, PVE'ye ssh acilmaz.
#
# Kullanim: gen-maintenance-inventory.sh --garage-ip <ip> --ct-id <id>
#
# Kaynaklar (tek gerçek zincir — inventories tofu'dan gelir, elle bakim yok):
#   ansible/inventory/hosts.ini.generated   → [k8s_master] satirlari (tofu uretir)
#   ansible/inventory/openbao.ini.generated → [openbao] satirlari (tofu uretir)
#   --garage-ip / --ct-id                   → garage2 = backup CT (tofu disi, chef verir)
# NOT: PVE maintenance kapsami disidir (vm-disk zamanlanmaz, exporter yok) —
#   pve-discovered.txt bu scriptin girdisi DEGILDIR, [pve] basilMAZ.
#
# Cikti: ansible/inventory/maintenance-<ctid>.ini.generated (0600, DO NOT EDIT)
#   (garaj basina ayri dosya — birlestirme yok, uzerine yazma cakismasi yok)
#
#   ansible-playbook -i inventory/maintenance-<ctid>.ini.generated playbooks/maintenance.yml

set -euo pipefail

GARAGE_IP=""
CT_ID=""
while [ $# -gt 0 ]; do
    case "$1" in
        --garage-ip) GARAGE_IP="${2:?--garage-ip bir IP gerektirir}"; shift 2 ;;
        --ct-id)     CT_ID="${2:?--ct-id bir CT ID gerektirir}"; shift 2 ;;
        *) echo "[HATA] bilinmeyen arguman: $1 (kullanim: $0 --garage-ip <ip> --ct-id <id>)" >&2; exit 1 ;;
    esac
done
[ -n "$GARAGE_IP" ] || { echo "[HATA] --garage-ip zorunlu (bu script sadece chef.sh'ten cagrilir)" >&2; exit 1; }
[[ "$CT_ID" =~ ^[0-9]+$ ]] || { echo "[HATA] --ct-id zorunlu ve sayisal olmali (bu script sadece chef.sh'ten cagrilir)" >&2; exit 1; }

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HOSTS_INI="${REPO_DIR}/ansible/inventory/hosts.ini.generated"
OPENBAO_INI="${REPO_DIR}/ansible/inventory/openbao.ini.generated"
OUT="${REPO_DIR}/ansible/inventory/maintenance-${CT_ID}.ini.generated"
TMP="${OUT}.tmp"

die() { echo "[HATA] $*" >&2; exit 1; }

[ -f "$HOSTS_INI" ]      || die "tofu envanteri yok: $HOSTS_INI (once tofu apply)"
[ -f "$OPENBAO_INI" ]    || die "tofu envanteri yok: $OPENBAO_INI (once tofu apply)"

# --- Bolum cekici: verilen ini'deki [section] altindaki host satirlarini al
section_lines() {
    local ini="$1" section="$2"
    awk -v sec="$section" '
        /^\[/ { hdr = $0; gsub(/^\[/, "", hdr); gsub(/\]$/, "", hdr); in_sec = (hdr == sec) }
        in_sec && NF && $0 !~ /^\[/ { print }
    ' "$ini"
}

MASTER_LINE="$(section_lines "$HOSTS_INI" k8s_master | head -1)"
OPENBAO_LINE="$(section_lines "$OPENBAO_INI" openbao | head -1)"
[ -n "$MASTER_LINE" ]   || die "[k8s_master] bolumu bos/kayip: $HOSTS_INI"
[ -n "$OPENBAO_LINE" ] || die "[openbao] bolumu bos/kayip: $OPENBAO_INI"

SSH_KEY="$(echo "$MASTER_LINE" | grep -oE 'ansible_ssh_private_key_file=[^ ]+' | cut -d= -f2-)"

# --- garage2 (backup CT) — IP chef'ten argumanla gelir, elle id/ip yok ---
# GARAGE_ENABLE_SSH denetimi BURADA YOK: [garage-backup] satirini ureten tek
# akis, chef.sh'in enable-ssh true kapanisidir (DRY: tek kaynak cagiran).
# .env'deki GARAGE_ENABLE_SSH bu akisi etkilemez - CLI --enable-ssh ezer.

cat > "$TMP" <<EOF
# Auto-generated by scripts/garage-setup/gen-maintenance-inventory.sh — DO NOT EDIT
# Kaynaklar: hosts.ini.generated + openbao.ini.generated + --garage-ip/--ct-id (chef.sh)
# Uretim: chef.sh cagirir (bagimsiz calistirilmaz)
# Kullanim:
#   ansible-playbook -i inventory/maintenance-<ctid>.ini.generated playbooks/maintenance.yml

[openbao]
${OPENBAO_LINE}

[k8s_master]
${MASTER_LINE}

# Garage2 — backup CT (tofu disi, chef.sh); §5 bucket/key bu host'ta (ssh)
[garage-backup]
garage2 ansible_host=${GARAGE_IP} ansible_user=root ${SSH_KEY:+ansible_ssh_private_key_file=${SSH_KEY}}

[all:vars]
deploy_env=dev
EOF

chmod 600 "$TMP"
mv -f "$TMP" "$OUT"
echo "[OK] $OUT uretildi:"
echo "  openbao      <- openbao.ini.generated"
echo "  k8s_master   <- hosts.ini.generated"
echo "  garage2      <- --garage-ip (${GARAGE_IP})"
