---
- name: Create per-role kubeconfigs
  ansible.builtin.include_tasks: gen-kubeconfig.yml
  loop: "{{ kubeconfig_roles }}"
  loop_control:
    loop_var: role_cfg
  vars:
    gen_kc_cluster_role: "{{ role_cfg.cluster_role }}"
    gen_kc_namespace: "{{ role_cfg.namespace }}"
    gen_kc_sa_name: "{{ role_cfg.name }}"
    gen_kc_filename: "{{ playbook_dir }}/../outputs/k8s/{{ role_cfg.filename }}.conf"
    gen_kc_cluster_wide: "{{ role_cfg.cluster_wide | default(false) }}"
